import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.testcellmasouthamptonaudiology.com/cellmaWEB/index.do');
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').fill('mayur.trainer');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('Welcome@123');
  await page.getByRole('button', { name: 'LOG IN' }).click();
  await page.getByRole('button', { name: 'Set' }).click();
  await page.locator('#homePageIconContainer > .homePageIcon').first().click();
  await page.getByLabel('Barcode:').fill('1774');
  await page.getByRole('cell', { name: 'Search', exact: true }).locator('a').click();
  await page.getByText('Select', { exact: true }).click();
  await page.getByRole('button', { name: 'Confirm Existing Details' }).click();
  await page.getByRole('cell', { name: 'Data entry Data entry', exact: true }).locator('a').click();
  await page.getByRole('cell', { name: 'X Index You are logged in as' }).locator('#closebtn').click();
  await page.locator('#assessment').click();
  await page.locator('#claId').selectOption('508');
  await page.getByRole('button', { name: 'Show' }).click();
  await page.getByRole('img', { name: 'Tests' }).click();
  await page.waitForTimeout(2000)
  await page.locator('#table50231').getByRole('cell', { name: 'Reviewed' }).click();
  await page.getByText('Normal', { exact: true }).click();
  await page.locator('#cestextarea_1').click();
  await page.locator('#cestextarea_1').fill('Comment');
  await page.locator('#edNotes').click();
  await page.locator('#edNotes').fill('Notes');
  await page.locator('#edSave').click();
  await page.locator('#table45370').getByRole('cell', { name: 'SIR' }).click();
  await page.locator('#ceslist_1').selectOption('791');
  await page.locator('#cestextarea_2').click();
  await page.locator('#cestextarea_2').fill('Comment Added');
  await page.locator('#edNotes').click();
 
  await page.locator('#edNotes').fill('Notes added');
  await page.locator('#edSave').click();
  await page.pause()
  await page.locator('#table49413').getByRole('cell', { name: 'NAMES' }).click();
  await page.waitForTimeout(2000)
  await page.locator('#ceslist_2').selectOption('965');
  await page.locator('#ceslist_3').selectOption('879');
  await page.locator('#ceslist_4').selectOption('879');
  await page.locator('#ceslist_5').selectOption('880');
  await page.locator('#ceslist_6').selectOption('880');
  await page.locator('#ceslist_7').selectOption('880');
  await page.locator('#ceslist_8').selectOption('880');
  await page.locator('#ceslist_9').selectOption('880');
  await page.locator('#ceslist_10').selectOption('965');
  await page.locator('#ceslist_11').selectOption('965')
  await page.waitForTimeout(2000)
  //await page.locator("xpath=//input[@name='cesd_12']").click()
  await page.waitForTimeout(4000)

  await page.locator('#ceslist_14').selectOption('965');
  await page.locator('#ceslist_15').selectOption('879');
  await page.locator('#ceslist_16').selectOption('879');
  await page.locator('#ceslist_17').selectOption('880');
  await page.locator('#ceslist_18').selectOption('879');
  await page.locator('#ceslist_19').selectOption('879');
  await page.locator('#ceslist_20').selectOption('880');
  await page.locator('#ceslist_21').selectOption('880');
  await page.locator('#ceslist_22').selectOption('879');
  await page.locator('#ceslist_23').selectOption('879');
  await page.locator('#ceslist_26').selectOption('880');
  await page.waitForTimeout(4000)
  //await page.locator("xpath=//input[@name='cesd_24']").click()
  await page.waitForTimeout(4000)
  await page.locator('#ceslist_27').selectOption('879');
  await page.locator('#ceslist_28').selectOption('879');
  await page.locator('#ceslist_29').selectOption('880');
  await page.locator('#ceslist_30').selectOption('879');
  await page.locator('#ceslist_31').selectOption('880');
  await page.locator('#ceslist_32').selectOption('879');
  await page.locator('#ceslist_33').selectOption('880');
  await page.locator('#ceslist_34').selectOption('879');
  await page.waitForTimeout(4000)
  //await page.locator("xpath=//input[@name='cesd_36']").click()
  await page.waitForTimeout(4000)  
  await page.locator('#ceslist_35').selectOption('880');
  await page.locator('#ceslist_38').selectOption('879');
  await page.locator('#ceslist_39').selectOption('880');
  await page.locator('#ceslist_40').selectOption('879');
  await page.locator('#ceslist_41').selectOption('880');
  await page.locator('#ceslist_42').selectOption('880');
  await page.locator('#ceslist_43').selectOption('880');
  await page.locator('#ceslist_44').selectOption('879');
  await page.locator('#ceslist_45').selectOption('880');
  await page.locator('#ceslist_46').selectOption('879');
  await page.locator('#ceslist_47').selectOption('880');
  await page.locator('#ceslist_50').selectOption('879');
  await page.locator('#ceslist_51').selectOption('880');
  await page.locator('#ceslist_52').selectOption('879');
  await page.locator('#ceslist_53').selectOption('879');
  await page.locator('#ceslist_54').selectOption('879');
  await page.locator('#ceslist_55').selectOption('879');
  await page.locator('#ceslist_56').selectOption('879');
  await page.locator('#ceslist_57').selectOption('879');
  await page.locator('#ceslist_58').selectOption('880');
  await page.locator('#ceslist_59').selectOption('879');
  await page.locator('#cestextarea_62').click();
  await page.locator('#cestextarea_62').fill('Good Score');
  await page.locator('#edNotes').click();
  await page.locator('#edNotes').fill('Added notes for testing');
  await page.locator('#edSave').click();
  await page.locator('#table50457').getByRole('cell', { name: 'NAMES Summary' }).click();
  await page.locator('#cesdate_1').click();
  await page.locator('#cesdate_1').fill('12');
  await page.locator('#cesdate_2').click();
  await page.locator('#cesdate_2').fill('13');
  await page.locator('#cesdate_3').click();
  await page.locator('#cesdate_3').fill('8');
  await page.locator('#cesdate_4').click();
  await page.locator('#cesdate_4').fill('11');
  await page.locator('#cesdate_5').click();
  await page.locator('#cesdate_5').fill('13');
  await page.getByRole('button', { name: 'Calculate', exact: true }).click();
  await page.locator('#cestextarea_7').click();
  await page.locator('#cestextarea_7').fill('Comment');
  await page.getByRole('cell', { name: 'Score for Milestone 1 12 Score for Milestone 2 13 Score for Milestone 3 8 Score for Milestone 4 11 Score for Milestone 5 13 Total score 57.0 Calculate Comments Comment Calculate All     Save', exact: true }).locator('#edSave').click();
  await page.locator('#table45496').getByRole('cell', { name: 'Adapted TAPs and LING' }).click();
  await page.locator('#ceslist_1').selectOption('692');
  await page.locator('#ceslist_2').selectOption('693');
  await page.locator('#ceslist_3').selectOption('693');
  await page.locator('#ceslist_4').selectOption('694');
  await page.locator('#ceslist_5').selectOption('693');
  await page.locator('#ceslist_6').selectOption('692');
  await page.locator('#ceslist_7').selectOption('693');
  await page.locator('#ceslist_8').selectOption('693');
  await page.locator('#cesdate_9').click();
  await page.locator('#cesdate_9').fill('7');
  await page.locator('#cesdate_10').click();
  await page.locator('#cesdate_10').fill('8');
  await page.locator('#cesdate_11').click();
  await page.locator('#cesdate_11').fill('5');
  await page.locator('#cesdate_12').click();
  await page.locator('#cesdate_12').fill('7');
  await page.locator('#cesdate_13').click();
  await page.locator('#cesdate_13').fill('5');
  await page.locator('#cesdate_14').click();
  await page.locator('#cesdate_14').fill('7');
  await page.locator('#cesdate_15').click();
  await page.locator('#cesdate_15').fill('8');
  await page.locator('#cesdate_16').click();
  await page.locator('#cesdate_16').fill('7');
  await page.locator('#cesdate_17').click();
  await page.locator('#cesdate_17').fill('8');
  await page.locator('#cesdate_18').click();
  await page.locator('#cesdate_18').fill('8');
  await page.locator('#cesdate_19').click();
  await page.locator('#cesdate_20').click();
  await page.locator('#cesdate_20').fill('7');
  await page.locator('#cesdate_21').click();
  await page.pause()
  await page.getByRole('button', { name: 'Calculate' }).nth(1).click();
  await page.locator('#cestextarea_22').click();
  await page.locator('#cestextarea_22').fill('Added comment');
  
 
  await page.locator('#edSave').click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.locator('#edSave').click();
  await page.getByRole('link', { name: 'Close' }).click();
  await page.locator('#table47259').getByRole('cell', { name: 'SpeechSounds2Talk' }).click();
  await page.locator('#cesdate_1').click();
  await page.getByRole('link', { name: '19' }).click();
  await page.locator('#cestextarea_3').click();
  await page.locator('#cestextarea_3').fill('Added comment');
  await page.locator('#edNotes').click();
  await page.locator('#edNotes').fill('Added Notes');
  await page.locator('#edSave').click();
  await page.locator('#table45366').getByRole('cell', { name: 'Babytalk tracker' }).click();
  await page.locator('#ceslist_1').selectOption('908');
  await page.locator('#ceslist_3').selectOption('909');
  await page.locator('#ceslist_5').selectOption('909');
  await page.locator('#ceslist_7').selectOption('909');
  await page.locator('#ceslist_9').selectOption('909');
  await page.locator('#ceslist_12').selectOption('909');
  await page.locator('#ceslist_13').selectOption('908');
  await page.locator('#ceslist_15').selectOption('908');
  await page.locator('#ceslist_17').selectOption('909');
  await page.locator('#ceslist_19').selectOption('909');
  await page.locator('#ceslist_21').selectOption('909');
  await page.locator('#ceslist_23').selectOption('909');
  await page.locator('#ceslist_25').selectOption('909');
  await page.locator('#ceslist_27').selectOption('909');
  await page.locator('#edNotes').click();
  await page.locator('#edNotes').fill('Added Notes');
  await page.locator('#edSave').click();
  await page.locator('#table45365').getByRole('cell', { name: 'LIFE-R' }).click();
  await page.locator('#ceslist_1').selectOption('614');
  await page.locator('#ceslist_2').selectOption('614');
  await page.locator('#ceslist_3').selectOption('615');
  await page.locator('#ceslist_4').selectOption('615');
  await page.locator('#ceslist_5').selectOption('616');
  await page.locator('#ceslist_6').selectOption('616');
  await page.locator('#ceslist_7').selectOption('613');
  await page.locator('#ceslist_8').selectOption('616');
  await page.locator('#ceslist_9').selectOption('614');
  await page.locator('#ceslist_10').selectOption('617');
  await page.locator('#ceslist_11').selectOption('615');
  await page.locator('#ceslist_12').selectOption('616');
  await page.locator('#ceslist_13').selectOption('616');
  await page.locator('#ceslist_14').selectOption('616');
  await page.locator('#ceslist_15').selectOption('617');
  await page.locator('#edNotes').click();
  await page.locator('#edNotes').fill('Added notes');
  await page.locator('#edSave').click();
  await page.locator('#table45506').getByRole('cell', { name: 'Early CaLL' }).click();
  await page.locator('#ceslist_1').selectOption('814');
  await page.locator('#ceslist_2').selectOption('426');
  await page.locator('#ceslist_3').selectOption('428');
  await page.locator('#ceslist_4').selectOption('820');
  await page.locator('#ceslist_5').selectOption('831');
  await page.locator('#ceslist_6').selectOption('839');
  await page.locator('#ceslist_7').selectOption('851');
  await page.locator('#ceslist_8').selectOption('858');
  await page.getByText('Severe illness etc.').click();
  await page.locator('#cestextarea_15').click();
  await page.locator('#cestextarea_15').fill('Added Comment');
  await page.locator('#edNotes').click();
  await page.locator('#edNotes').fill('Added Notes');
  await page.locator('#edSave').click();
 // await page.goto('https://www.testcellmasouthamptonaudiology.com/cellmaWEB/SaveQuestionsResult.do');
  await page.locator('#table46151').getByRole('cell', { name: 'Video' }).click();
  await page.locator('#cesdate_1').click();
  await page.locator('#cesdate_1').fill('8');
  await page.locator('#edNotes').click();
  await page.locator('#edNotes').fill('Added Notes');
  await page.locator('#edSave').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#overview').click();
  await page.locator('#overview').fill('Added Oveview');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#table44189').getByRole('cell', { name: 'Safeguarding Query' }).click();
  await page.locator('#edNotes').click();
  await page.locator('#edNotes').fill('Added Query');
  await page.locator('#edSave').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('Click to view details entered').click();
  await page.locator('#overview').click();
  await page.locator('#overview').fill('Add Last Overview');
  //await page.goto('https://www.testcellmasouthamptonaudiology.com/cellmaWEB/MarkAssessmentAsComplete.do');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('img', { name: 'Riomed\'s CELLMA' }).click();
  await page.locator('#closebtnVersion').click();
  await page.getByLabel('').locator('div').first().click();
  await page.getByLabel('').locator('div').first().click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'LOG OUT' }).click();
});